# auth-jpa-defaults.properties
auth.jpa.dll-auto=update
auth.jpa.database-platform-dialect=org.hibernate.dialect.PostgreSQLDialect
auth.jpa.table-prefix=auth_

auth.jpa.table.mapping.users=users
auth.jpa.table.mapping.refresh-tokens=refresh_tokens
